package com.github.catatafishen.ideagentforcopilot.bridge;

import com.intellij.openapi.diagnostic.Logger;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Ensures that plugin instructions are present in the project's CLAUDE.md
 * before the Claude Code CLI process starts.
 *
 * <p>Claude Code reads {@code CLAUDE.md} at the project root and injects it
 * into the model context. This class prepends plugin instructions (tool guidance,
 * quick-reply syntax, etc.) on first run.</p>
 *
 * <p>Thread-safe: uses a class-level lock so concurrent calls don't race.</p>
 */
public final class ClaudeInstructionsManager {
    private static final Logger LOG = Logger.getInstance(ClaudeInstructionsManager.class);

    /**
     * Sentinel comment used to detect prior prepend of plugin instructions.
     */
    public static final String INSTRUCTIONS_SENTINEL =
        "---\n> ⚙️ Auto-generated by IDE Agent for Copilot — do not edit this section";
    private static final String INSTRUCTIONS_END =
        "> End of auto-generated instructions\n---";

    private static final Object LOCK = new Object();

    private ClaudeInstructionsManager() {
    }

    /**
     * Ensures plugin instructions exist in the project's CLAUDE.md.
     * Safe to call multiple times — uses a sentinel comment to detect prior prepend.
     *
     * @param projectBasePath the project root directory, or null to skip
     */
    public static void ensureInstructions(@Nullable String projectBasePath) {
        if (projectBasePath == null) return;

        synchronized (LOCK) {
            try {
                Path claudeMd = Path.of(projectBasePath, "CLAUDE.md");
                Path dotClaudeFile = Path.of(projectBasePath, ".claude", "instructions.md");
                Path targetFile;
                if (Files.isRegularFile(claudeMd)) {
                    targetFile = claudeMd;
                } else if (Files.isRegularFile(dotClaudeFile)) {
                    targetFile = dotClaudeFile;
                } else {
                    targetFile = claudeMd;
                }

                String pluginInstructions = loadPluginInstructions();

                if (Files.isRegularFile(targetFile)) {
                    String existing = Files.readString(targetFile, StandardCharsets.UTF_8);
                    if (existing.contains(INSTRUCTIONS_SENTINEL)) {
                        return;
                    }
                    String merged = pluginInstructions + "\n\n" + existing;
                    Files.writeString(targetFile, merged, StandardCharsets.UTF_8);
                    LOG.info("Prepended plugin instructions to existing " + targetFile);
                } else {
                    Path parent = targetFile.getParent();
                    if (parent != null) {
                        Files.createDirectories(parent);
                    }
                    Files.writeString(targetFile, pluginInstructions, StandardCharsets.UTF_8);
                    LOG.info("Created " + targetFile + " with plugin instructions");
                }
            } catch (IOException e) {
                LOG.warn("Failed to ensure CLAUDE.md", e);
            }
        }
    }

    @NotNull
    private static String loadPluginInstructions() {
        try (InputStream is = ClaudeInstructionsManager.class.getResourceAsStream("/default-startup-instructions.md")) {
            if (is != null) {
                String instructions = new String(is.readAllBytes(), StandardCharsets.UTF_8);
                return INSTRUCTIONS_SENTINEL + "\n\n" + instructions + "\n\n" + INSTRUCTIONS_END;
            }
        } catch (IOException e) {
            LOG.warn("Failed to load default startup instructions resource", e);
        }
        return INSTRUCTIONS_SENTINEL + "\n\nYou are running inside an IntelliJ IDEA plugin with IDE tools.\n\n" + INSTRUCTIONS_END;
    }
}
